In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

digits = load_digits()

In [2]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.1)


In [3]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)


C:\Users\Pruthvik Kashyap S\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9722222222222222

In [4]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)


0.9944444444444445

In [24]:
rf = RandomForestClassifier(n_estimators = 40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)


0.9198664440734557

In [25]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [26]:
for train_index, test_index, in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [27]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [28]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9549248747913188

In [29]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [30]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test,  y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                            digits.target[train_index], digits.target[test_index]
    
    scores_l.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))
    

C:\Users\Pruthvik Kashyap S\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Pruthvik Kashyap S\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#log

In [31]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [32]:
scores_rf

[0.9348914858096828, 0.9432387312186978, 0.9248747913188647]

In [33]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [34]:
from sklearn.model_selection import cross_val_score

In [36]:
cross_val_score(LogisticRegression(),digits.data, digits.target)

C:\Users\Pruthvik Kashyap S\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Pruthvik Kashyap S\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#log

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [38]:
cross_val_score(SVC(),digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [40]:
cross_val_score(RandomForestClassifier(n_estimators = 40),digits.data, digits.target)

array([0.94166667, 0.88333333, 0.9637883 , 0.95543175, 0.91643454])

In [44]:
cross_val_score(RandomForestClassifier(n_estimators = 10),digits.data, digits.target)

array([0.9       , 0.85555556, 0.90250696, 0.94150418, 0.8718663 ])

In [45]:
#Exercise

In [68]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier


In [69]:
iris = load_iris()

In [70]:
l_scores = cross_val_score(LogisticRegression(), iris.data, iris.target)

C:\Users\Pruthvik Kashyap S\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [71]:
np.average(l_scores)

0.9733333333333334

In [72]:
svm_scores = cross_val_score(SVC(), iris.data, iris.target)

In [73]:
np.average(svm_scores)

0.9666666666666666

In [74]:
rf_scores = cross_val_score(RandomForestClassifier(), iris.data, iris.target)

In [75]:
np.average(rf_scores)

0.9666666666666668