In [11]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [12]:
df = pd.read_csv('housing.csv')
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [13]:
meidan_bedroom = int(df.bedroom.median())

In [14]:
df.bedroom = df.bedroom.fillna(meidan_bedroom)
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [15]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedroom','age']], df.price)


# price = m1 * area + m2 * bedroom + m3 * age + b

LinearRegression()

In [16]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [17]:
reg.intercept_

383725.0

In [18]:
reg.predict([[3000,3,40]])   # 3000 sqft, 3 bedrooms, 40 yrs old

C:\Users\Pruthvik Kashyap S\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [19]:
reg.predict([[2500,4,5]])

C:\Users\Pruthvik Kashyap S\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])

In [20]:
#Exercise

In [41]:
df = pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [42]:
pip install word2number


Note: you may need to restart the kernel to use updated packages.


In [43]:
from word2number import w2n
df['experience']

0       NaN
1       NaN
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [44]:
df['experience']  = df.experience.fillna('zero')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [46]:
df.experience = df.experience.apply(w2n.word_to_num) 
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [49]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(int(df['test_score(out of 10)'].median()))
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [55]:
reg2 = linear_model.LinearRegression()
reg2.fit(df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df['salary($)'])

LinearRegression()

In [56]:
reg2.predict([[12,10,10]])

C:\Users\Pruthvik Kashyap S\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])